spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/office_library
    username: postgres
    password: "${DB_PASS}"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    com.library: DEBUG
    org.springframework.web: DEBUG
